# Generated by Django 4.1.6 on 2023-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studentdetail',
            index=models.Index(fields=['name'], name='student_inf_name_3d456d_idx'),
        ),
        migrations.AlterModelTable(
            name='studentdetail',
            table='student_information',
        ),
    ]
