# Generated by Django 3.2 on 2023-02-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_studentdetail_created_on_studentdetail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
