# Generated by Django 3.2 on 2023-02-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_studentdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
