# Generated by Django 3.2 on 2023-02-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20230214_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
