# Generated by Django 3.2 on 2023-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20230214_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
